# Note: If you want to deploy to a GitHub user site (user.github.io), change baseurl to /
baseurl:
title: deRSE19
author: de-RSE e.V. - Gesellschaft für Forschungssoftware
email: vorstand [at] de-rse [dot] org
description: Website of de-RSE e.V. - Gesellschaft für Forschungssoftware
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
permalink: /blog/:categories/:year/:month/:day/:title.html
timezone: Europe/Berlin
excerpt_separator: <!--more-->
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
plugins_dir:
  - jekyll-feed
